name: check
on: [push]
jobs:
  check:
    name: Check ${{ matrix.workdir }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workdir: [app, csi]
    defaults:
      run:
        working-directory: ${{ matrix.workdir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Just
        uses: extractions/setup-just@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ${{ matrix.workdir }}/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          working-directory: ${{ matrix.workdir }}
      - name: Test
        run: just test_short
      - name: Build
        run: just build
